salesforceServer:
  consumerKey: "![Nt1YhjZ+pC4HO5xh99gIWtbXcUo97gMgpil51b3MzNqB/Dx8Rvh+hAlOlQA4zRET9PErfRdZda1WVez0wpzsTUFO8WzSnyWLf/eY4VQqGBxEKZu4ftnMzQ==]"
  keyStorePassword: "![EpYZiC8QQfJrjuDVQBZjIycZ1bw4WnUe]"
  userName: "![zPdhcuT6KyimyUeQznmD9OoEgBuv0TUfIaxMsAeN9j12XcNKEqMAnA==]"
  certificateAlias: "![8fibUWFTGjdnpCR++dcniWjPucnzGLxT]"