#%RAML 1.0 DataType
type: object
properties:
  abandoned_checkout_url?:
    type: string
  updated_at?:
    type: datetime
  closed_at?:
    type: datetime
  created_at?:
    type: datetime
  currency?:
    type: string
  customer_id?:
    type: number
  id?:
    type: number
  landing_site?:
    type: string
  note?:
    type: string
  phone?:
    type: string
  referring_site?:
    type: string
  source_name?:
    type: string
  subtotal_price?:
    type: number
  total_discounts?:
    type: number
  total_duties?:
    type: number
  total_line_items_price?:
    type: number
  total_price?:
    type: number
  total_tax?:
    type: number
  billing_address_id?:
    type: number