#%RAML 1.0 DataType
type: object
properties:
  created_at:
    type: datetime
  customer_id:
    type: number
  updated_at:
    type: datetime
  email_marketing_consent_state:
    type: string
  email_marketing_consent_updated_at:
    type: datetime
  email:
    type: string