#%RAML 1.0 DataType
type: object
properties:
  active_products?:
    type: string
  updated_at?:
    type: datetime
  active_subscriber?:
    type: string
  active_subscription_count?:
    type: number
  active_subscription_variant_ids?:
    type: string
  all_next_charge_dates?:
    type: string
  cancelled_products?:
    type: string
  cancelled_sku?:
    type: string
  cancelled_subscription_count?:
    type: number
  cancelled_subscription_variant_ids?:
    type: string
  created_at?:
    type: datetime
  current_contraception_method?:
    type: string
  customer_charge_count?:
    type: number
  email?:
    type: string
  email_marketing_consent_state?:
    type: string
  email_marketing_consent_updated_at?:
    type: datetime
  first_charge_processed_at?:
    type: datetime
  first_name?:
    type: string
  id?:
    type: number
  last_name?:
    type: string
  last_order_id?:
    type: number
  last_order_name?:
    type: string
  next_charge_date?:
    type: datetime
  orders_count?:
    type: number
  phone?:
    type: string
  preferred_language?:
    type: string
  queued_charge_count?:
    type: number
  ReCharge_Subscriptions?:
    type: string
  sms_marketing_consent_collected_from?:
    type: string
  sms_marketing_consent_state?:
    type: string
  sms_marketing_consent_updated_at?:
    type: datetime
  state?:
    type: string
  total_spent?:
    type: number
  active_sku?:
    type: string