#%RAML 1.0 DataType
type: object
properties:
  boy_girl?:
    type: string
  childs_name?:
    type: string
  created_at?:
    type: datetime
  customer_id?:
    type: number
  would_you_be_interested_in?:
    type: string
  feeding_intention?:
    type: string
  id?:
    type: string
  my_baby?:
    type: string
  relationship_to_child?:
    type: string
  date_of_birth?:
    type: date-only