#%RAML 1.0 DataType
type: object
properties:
  address1?:
    type: string
  address2?:
    type: string
  city?:
    type: string
  company?:
    type: string
  country?:
    type: string
  country_code?:
    type: string
  zip?:
    type: string
  default?:
    type: string
  id?:
    type: number
  phone?:
    type: string
  province?:
    type: string
  province_code?:
    type: string
  customer_id?:
    type: number