#%RAML 1.0 DataType
type: object
properties:
  fulfillment_status?:
    type: string
  id?:
    type: number
  order_id?:
    type: number
  variant_id?:
    type: number
  quantity?:
    type: number
  total_discount?:
    type: number
  price?:
    type: number