#%RAML 1.0 DataType
type: object
properties:
  app_id?:
    type: number
  updated_at?:
    type: datetime
  cancelled_at?:
    type: datetime
  cancel_reason?:
    type: string
  closed_at?:
    type: datetime
  confirmation_number?:
    type: string
  created_at?:
    type: datetime
  currency?:
    type: string
  customer_id?:
    type: number
  email?:
    type: string
  financial_status?:
    type: string
  fulfillment_status?:
    type: string
  id?:
    type: number
  name?:
    type: string
  note?:
    type: string
  order_number?:
    type: number
  phone?:
    type: string
  po_number?:
    type: string
  referring_site?:
    type: string
  shipping_address_id?:
    type: number
  source_identifier?:
    type: string
  source_name?:
    type: string
  subtotal_price?:
    type: number
  total_discounts?:
    type: number
  total_outstanding?:
    type: number
  total_price?:
    type: number
  total_tax?:
    type: number
  total_weight?:
    type: number
  billing_address_id?:
    type: number