#%RAML 1.0 DataType
type: object
properties:
  created_at?:
    type: datetime
  id?:
    type: number
  product_type?:
    type: string
  vendor?:
    type: string
  title?:
    type: string
  updated_at?:
    type: datetime
  status?:
    type: string