#%RAML 1.0 DataType
type: object
properties:
  cancellation_reason?:
    type: string
  created_at?:
    type: datetime
  customer_id?:
    type: number
  external_product_id?:
    type: number
  external_variant_id?:
    type: number
  is_prepaid?:
    type: string
  subscription_id?:
    type: number
  order_interval_frequency?:
    type: number
  order_interval_unit?:
    type: string
  price?:
    type: number
  product_title?:
    type: string
  sku?:
    type: string
  status?:
    type: string
  next_charge_scheduled_at?:
    type: datetime